### ISSUE TITLE
3D object detection

### ISSUE THREAD

**Issue by CatOneTwo** [ai4ce/DiscoNet#2]
Hi, thank you for your good job!
I noticed that DiscoNet is implemented on a one-stage 3D object detection model, have you conducted it on a two-stage 3D object detection model?

**Comment by RoboticsYimingLi** [comment]
We have not conducted that, yet if you are interested, feel free to contribute to our open-source lib: https://github.com/coperception/coperception! We are including more single-agent detector backbones such as anchor-free methods.
