### ISSUE TITLE
Question about running train_codet.py

### ISSUE THREAD

**Issue by Sun1boy** [ai4ce/DiscoNet#5]
Hi, thanks for your excellent work!
When I run command make make train_disco, I got the following error:
![image](https://github.com/ai4ce/DiscoNet/assets/119661643/d81211c8-dd09-4cc8-ba4a-375a47f8b46c)
and the error is:
![image](https://github.com/ai4ce/DiscoNet/assets/119661643/89faec03-09bb-4684-b657-d0af87b11e4a)
The dataset is the V2X-Sim2.0(parsed) provided by https://github.com/ai4ce/DiscoNet
![image](https://github.com/ai4ce/DiscoNet/assets/119661643/c31e09f4-43af-40bb-ba38-75e54d0f7ecf)
In the V2X-Sim2.0(parsed) is:
![image](https://github.com/ai4ce/DiscoNet/assets/119661643/d6b8afad-3418-4935-a6be-a8af59b64c3c)

My system is Ubuntu 22.04 , and python version is 3.7.16.
My cuda version is 11.2
Could you tell me what the problem is?

**Comment by dekunma** [comment]
Did you make any changes to the code? As of now I'm not able to reproduce your error using the V2X-Sim-2-mini dataset (unfortunately I don't have enough computational resources at hand to run the full dataset lol, but the effect should be the same).
Please try to see if the error persists with the mini dataset. If there's no error with the mini dataset, I'll look into the full dataset.
![image](https://github.com/ai4ce/DiscoNet/assets/53892579/d36525d0-3fa7-4192-8e7f-dd43cb37a4a4)

**Comment by Sun1boy** [comment]
I haven't change the code before. 
The problem seems to be that two graphics cards cannot be used at the same time. I change the number of graphics cards used and it seems to run.
![image](https://github.com/ai4ce/DiscoNet/assets/119661643/551d2150-d89a-4fdc-b108-e4c7fcce3660)

**Comment by dekunma** [comment]
Ah yes, currently `coperception` does not support training across multiple graphic cards. 
Thanks for pointing this out and glad that the problem has been resolved.
